### ISSUE TITLE
What is the root user password?

### ISSUE THREAD

**Issue by shad1ao** [koyeb/example-nextjs#5]
I need to install some software using apt, but I don't have root access.

**Comment by brmzkw** [comment]
Hello,

The best thing to do is to form this repository, update the [Dockerfile](https://github.com/koyeb/example-nextjs/blob/main/Dockerfile#L15) and under `FROM base AS runner`, add `RUN apt-get install -y <your package>`.

Does it solve your issue?

**Comment by brmzkw** [comment]
Feel free to reopen if the issue persists
